-- MySQL Script generated by MySQL Workbench
-- jue 11 abr 2018 22:55:34 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AYD1_Practica3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AYD1_Practica3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AYD1_Practica3` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `AYD1_Practica3` ;

-- -----------------------------------------------------
-- Table `AYD1_Practica3`.`TIPO`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `AYD1_Practica3`.`TIPO` (
    `cod_tipo`      INT NOT NULL AUTO_INCREMENT COMMENT '',
    `descripcion`   VARCHAR(50) NOT NULL COMMENT '',
    PRIMARY KEY (`cod_tipo`) COMMENT '')
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `AYD1_Practica3`.`USUARIO`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `AYD1_Practica3`.`USUARIO` (
    `codigo`       INT NOT NULL COMMENT '',
    `nombre`       VARCHAR(100) NOT NULL COMMENT '',
    `apellido`     VARCHAR(100) NOT NULL COMMENT '',
    `nickname`     VARCHAR(50) NOT NULL COMMENT '',
    `correo`       VARCHAR(100) NOT NULL COMMENT '',
    `contrasenia`   VARCHAR(200) NOT NULL COMMENT '',
    PRIMARY KEY (`codigo`) COMMENT '')
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `AYD1_Practica3`.`CUENTA`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `AYD1_Practica3`.`CUENTA` (
    `no_cuenta`   INTEGER NOT NULL COMMENT '',
    `codigo`      INTEGER NOT NULL COMMENT '',
    `cantidad`    FLOAT(10) NOT NULL COMMENT '',
    PRIMARY KEY (`no_cuenta`)  COMMENT '',
    INDEX `fk_CUENTA_USUARIO_idx` (`codigo` ASC)  COMMENT '',
    CONSTRAINT `fk_CUENTA_USUARIO`
    FOREIGN KEY (`codigo`)
    REFERENCES `AYD1_Practica3`.`USUARIO` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `AYD1_Practica3`.`TRANSACCION`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `AYD1_Practica3`.`TRANSACCION` (
	`cod`           INT NOT NULL AUTO_INCREMENT COMMENT '',
    `no_cuenta`     INT NOT NULL COMMENT '',
    `fecha_hora`    DATETIME NOT NULL COMMENT '',
    `monto`         FLOAT(10) NOT NULL COMMENT '',
    `descripcion`   VARCHAR(100) COMMENT '',
    `estado`   		CHAR NOT NULL COMMENT '',
    `cod_tipo`      INT NOT NULL COMMENT '',
    PRIMARY KEY (`cod`) COMMENT '',
    INDEX `fk_TRANSACCION_CUENTA_idx` (`no_cuenta` ASC)  COMMENT '',
    INDEX `fk_TRANSACCION_TIPO_idx` (`cod_tipo` ASC)  COMMENT '',
    CONSTRAINT `fk_TRANSACCION_CUENTA`
    FOREIGN KEY (`no_cuenta`)
    REFERENCES `AYD1_Practica3`.`CUENTA` (`no_cuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_TRANSACCION_TIPO`
    FOREIGN KEY (`cod_tipo`)
    REFERENCES `AYD1_Practica3`.`TIPO` (`cod_tipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- `AYD1_Practica3`.`TRANSFERENCIA`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `AYD1_Practica3`.`TRANSFERENCIA` (
    `no_cuenta_origen`    INTEGER NOT NULL COMMENT '',
    `no_cuenta_destino`   INTEGER NOT NULL COMMENT '',
    `fecha_hora`          DATETIME NOT NULL COMMENT '',
    `monto`               FLOAT(10) NOT NULL COMMENT '',
    PRIMARY KEY (`no_cuenta_origen`, `no_cuenta_destino`, `fecha_hora`) COMMENT '',
    INDEX `fk_TRANSFERENCIA_CUENTA1_idx` (`no_cuenta_origen` ASC)  COMMENT '',
    INDEX `fk_TRANSFERENCIA_CUENTA2_idx` (`no_cuenta_destino` ASC)  COMMENT '',
    CONSTRAINT `fk_TRANSFERENCIA_CUENTA1`
    FOREIGN KEY (`no_cuenta_origen`)
    REFERENCES `AYD1_Practica3`.`CUENTA` (`no_cuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TRANSFERENCIA_CUENTA2`
    FOREIGN KEY (`no_cuenta_destino`)
    REFERENCES `AYD1_Practica3`.`CUENTA` (`no_cuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO TIPO(descripcion) VALUES ('Crédito');
INSERT INTO TIPO(descripcion) VALUES ('Débito');
INSERT INTO USUARIO(codigo, nombre, apellido, nickname, correo, contrasenia) VALUES (1000, 'Glen', 'Calel', 'gl3ncal3l', 'gl3ncal3l@gmail.com', '1234');
INSERT INTO CUENTA(no_cuenta, codigo, cantidad) VALUES (10000, 1000, 1000);

INSERT INTO USUARIO(codigo, nombre, apellido, nickname, correo, contrasenia) VALUES (1001, 'Carlos', 'Perlta', 'carlosperalta', 'carlosperalta@gmail.com', '1234');
INSERT INTO CUENTA(no_cuenta, codigo, cantidad) VALUES (10001, 1001, 0.0);

INSERT INTO USUARIO(codigo, nombre, apellido, nickname, correo, contrasenia) VALUES (1, 'admin', 'admin', 'admin', 'admin@gmail.com', '1234admin');
INSERT INTO CUENTA(no_cuenta, codigo, cantidad) VALUES (1, 1, 0);


